linters:
  csslint: {  }
  phpcs:
    standard: PSR2
    fixer: true
  shellcheck:
    shell: bash
files:
  ignore:
    - 'bower_components/*'
    - 'migrations/*'
    - 'src/Security/*'
    - 'node_modules/*'
    - 'vendor/*'
fixers:
  enable: true
